(** The ANNOTATED syntax of CIC^-, generated by Sulfur.

    This file requires Syntax/Erased.v although it uses nothing from it: the
    dependency forces the LOAD ORDER.  Sulfur keeps one generated signature at
    a time, so wherever both algebras are loaded this one is loaded last and
    is the signature [rasimpl] works with -- which is what the de Bruijn work
    of the typing rules needs.

    LEVEL ANNOTATIONS.  Every type former carries the level it lives at, and
    its components may sit at any levels below, INDEPENDENTLY of each other:
    `pi k A B : univ (S k) k` for A : univ (S i) i and B : univ (S j) j with
    i <= k and j <= k.  The universe lift is then one step on the annotation
    and computes on every closed type expression. *)

From CICM Require Export Syntax.Erased.
From Sulfur Require Export All.

Sulfur Generate
{{
  tm(var_tm) : Type

  (* Two lambdas and two applications, one pair for Pi and one for the
     impredicative forall.  They erase identically, so this costs nothing on
     realisers; the point is UNICITY OF TYPING.  With a single lambda,
     `lam A t` inhabits both `pi A (prf p)` and `prf (all A p)`, so a term's
     type -- and with it the universe level -- is not determined by its
     syntax.  plam and papp are NOT annotated: a proof term is interpreted by
     one clause, which says nothing about the subject. *)
  lam    : {{nat}} -> tm -> (bind tm in tm) -> (bind tm in tm) -> tm
  plam   : tm -> (bind tm in tm) -> tm
  app    : tm -> (bind tm in tm) -> tm -> tm -> tm
  papp   : tm -> tm -> tm
  pair   : {{nat}} -> tm -> (bind tm in tm) -> tm -> tm -> tm
  fst    : tm -> (bind tm in tm) -> tm -> tm
  snd    : tm -> (bind tm in tm) -> tm -> tm
  pi     : {{nat}} -> tm -> (bind tm in tm) -> tm
  sig_   : {{nat}} -> tm -> (bind tm in tm) -> tm

  (* W types, on exactly the pattern of Pi and Sigma.  `wrec A B C s w`
     carries the scrutinee's W type (A and B) as `app` and `fst` carry their
     Pi/Sigma: natrec needs no such annotation because its scrutinee's type is
     the CONSTANT nat_, whereas a tree's is `wt k A B`.  The step carries its
     own three binders -- label, branching function, induction hypothesis --
     as natrec's carries two: a step written as a function would have a TYPE,
     and the interpretation would have to match it, including level
     annotations that are not part of the subject. *)
  wt     : {{nat}} -> tm -> (bind tm in tm) -> tm
  sup    : {{nat}} -> tm -> (bind tm in tm) -> tm -> tm -> tm
  wrec   : tm -> (bind tm in tm) -> (bind tm in tm) -> (bind tm tm tm in tm) -> tm -> tm

  nat_   : {{nat}} -> tm
  zero   : {{nat}} -> tm
  succ   : tm -> tm
  natrec : (bind tm in tm) -> tm -> (bind tm tm in tm) -> tm -> tm

  univ   : {{nat}} -> {{nat}} -> tm
  (* the TYPE lift, annotated with the universe its subject lives in, and the
     TERM lift, annotated with the type it lifts *)
  up     : {{nat}} -> tm -> tm
  uptm   : tm -> tm -> tm

  prop   : {{nat}} -> tm
  prf    : {{nat}} -> tm -> tm
  (* the impredicative forall is annotated with the level of the PROPOSITION
     it forms, which its domain does not determine *)
  all    : {{nat}} -> tm -> (bind tm in tm) -> tm
  false_ : {{nat}} -> tm
  absurd : tm -> tm -> tm

  (* Eq is in the syntax but has NO typing rule: Layer1/BadTransp.v refutes
     the blueprint's transport rule. *)
  eqty   : tm -> tm -> tm -> tm
  refl   : tm -> tm -> tm
  transp : tm -> (bind tm in tm) -> tm -> tm -> tm -> tm -> tm
}}.

(* the boilerplate rasimpl needs, now aimed at the annotated syntax *)
Ltac2 Set aunfold_list as old := fun () => List.append (constants up_ren, up_subst) (old ()).
From Ltac2 Require Import Rewrite.
Ltac2 Set rasimpl_matches := fun () =>
  Strategy.choice (Strategy.matches pat:(rename _ _)) (Strategy.matches pat:(substitute _ _)).

(* The annotated syntax owns the notations: this is where the de Bruijn work
   happens.  The erased side uses the explicit names of Syntax/Erased.v. *)
Module Export AnnNotations.
  Notation "t ⟨ r ⟩" := (rename r t) (at level 7, left associativity, format "t ⟨ r ⟩").
  Notation "t [ s ]" := (substitute s t) (at level 7, left associativity, format "t [ s ]").
  Notation "a .: s" := (scons a s) (at level 60, right associativity).
  Notation "a '..'" := (a .: sid) (at level 1).
  (* a renaming used as the tail of a substitution.  Shifts must be written in
     the substitution algebra like this -- as a raw lambda
     (fun i => var_tm (S (S i))) rasimpl cannot push a composition through
     them, which is exactly what made the W step's equations intractable. *)
  Notation "a '.:s' r" := (scons a (rscomp r sid)) (at level 60, right associativity).
End AnnNotations.

Lemma rename_id t : t ⟨rid⟩ = t.
Proof. rasimpl; reflexivity. Qed.

Lemma subst_id t : t [sid] = t.
Proof. rasimpl; reflexivity. Qed.
