(** The ERASED calculus, generated by Sulfur.

    Sulfur keeps ONE generated signature at a time (the plugin's [saved_ops]
    is a single reference, set when a library is loaded), so the two term
    algebras of this development live in two files, and [Syntax/Ann.v]
    requires this one.  The dependency forces the load order: wherever both
    are loaded, the annotated syntax is loaded LAST and is therefore the
    signature [rasimpl] reifies with.  Everything the erased side needs from
    the substitution algebra is proved HERE, where [rasimpl] is aimed at it. *)

From Sulfur Require Export All.

Sulfur Generate
{{
  etm(var_etm) : Type

  elam    : (bind etm in etm) -> etm
  eapp    : etm -> etm -> etm
  epair   : etm -> etm -> etm
  efst    : etm -> etm
  esnd    : etm -> etm
  epi     : etm -> etm -> etm
  esig    : etm -> etm -> etm
  (* W: the type former, the constructor, and the recursor whose step is a
     curried function of the label, the branching function and the induction
     hypothesis (as enatrec's is of the predecessor and the recursive
     result). *)
  ew      : etm -> etm -> etm
  esup    : etm -> etm -> etm
  ewrec   : etm -> etm -> etm
  enat    : etm
  ezero   : etm
  esucc   : etm -> etm
  enatrec : etm -> etm -> etm -> etm
  euniv   : {{nat}} -> etm
  eprop   : etm
  eprf    : etm -> etm
  eall    : etm -> etm -> etm
  efalse  : etm
  estar   : etm
  eerr    : etm
  eeqty   : etm -> etm -> etm -> etm
}}.

(* The boilerplate rasimpl needs; RASimpl.v marks it as a FIXME ("should be
   automatic").  It is aimed at THIS signature only while this file is the
   last one loaded, which is why the erased-side equations are proved here. *)
Ltac2 Set aunfold_list as old := fun () => List.append (constants up_ren, up_subst) (old ()).
From Ltac2 Require Import Rewrite.
Ltac2 Set rasimpl_matches := fun () =>
  Strategy.choice (Strategy.matches pat:(rename _ _)) (Strategy.matches pat:(substitute _ _)).

(* The erased side gets EXPLICIT names rather than notations: the annotated
   syntax owns the notations, since that is where the de Bruijn work is. *)
Definition ren_etm : ren -> etm -> etm := rename.
Definition subst_etm : (nat -> etm) -> etm -> etm := substitute.
Definition up_etm : (nat -> etm) -> (nat -> etm) := up_subst.

(* Notations for the erased side, NOT exported: a file that touches both
   algebras uses the explicit names above, and only the erased-only files
   (Reduction/) import these. *)
(* renamings are SHARED by the two algebras (both are nat -> nat), so the
   shift is declared once, here. *)
Notation "↑" := rshift.

(* the one-point substitution, used by the beta rules of the erased calculus *)
Definition esub1 (u : etm) : nat -> etm := scons u sid.

Lemma ext_etm (s t : nat -> etm) : (forall i, s i = t i) -> forall u, subst_etm s u = subst_etm t u.
Proof. intros H u; unfold subst_etm; eapply congr_substitute; [exact H | reflexivity]. Qed.

Lemma subst_etm_id u : subst_etm sid u = u.
Proof. unfold subst_etm; rasimpl; reflexivity. Qed.

(* the three composition laws layer 1 uses *)
Lemma subst_ren_etm s r u :
  subst_etm s (ren_etm r u) = subst_etm (rscomp r s) u.
Proof. unfold subst_etm, ren_etm; rasimpl; reflexivity. Qed.

Lemma ren_subst_etm r s u :
  ren_etm r (subst_etm s u) = subst_etm (srcomp s r) u.
Proof. unfold subst_etm, ren_etm; rasimpl; reflexivity. Qed.

Lemma subst_subst_etm s t u :
  subst_etm t (subst_etm s u) = subst_etm (scomp s t) u.
Proof. unfold subst_etm; rasimpl; reflexivity. Qed.

(* the two shapes Layer1/Fundamental.v states by hand *)
Lemma subst_shift_etm s t : subst_etm s (ren_etm rshift t) = subst_etm (rscomp rshift s) t.
Proof. apply subst_ren_etm. Qed.

Lemma subst_up_shift_etm s t :
  subst_etm (up_etm s) (ren_etm rshift t) = ren_etm rshift (subst_etm s t).
Proof. unfold subst_etm, ren_etm, up_etm; rasimpl; reflexivity. Qed.

(* The remaining shapes Layer1/ needs.  They are all here rather than there
   because rasimpl reifies with the LAST generated signature, which is the
   annotated one wherever both algebras are loaded; on the erased side the
   only usable equations are the ones proved in this file. *)

(* a one-point substitution absorbed into an outer one, and cancelled by an
   opened binder *)
Lemma subst_sub1_etm s u t :
  subst_etm s (subst_etm (esub1 u) t) = subst_etm (scons (subst_etm s u) s) t.
Proof. unfold subst_etm, esub1; rasimpl; reflexivity. Qed.

Lemma subst_up_sub1_etm s u t :
  subst_etm (esub1 u) (subst_etm (up_etm s) t) = subst_etm (scons u s) t.
Proof. unfold subst_etm, up_etm, esub1; rasimpl; reflexivity. Qed.

(* a shift cancelled by a cons: the erasures of the W helpers are full of
   these, every binder of the step's context shifting the tree type past one
   more variable *)
Lemma subst_sub1_shift_etm u t : subst_etm (esub1 u) (ren_etm rshift t) = t.
Proof. unfold subst_etm, ren_etm, esub1; rasimpl; reflexivity. Qed.

Lemma subst_cons_shift_etm u s t :
  subst_etm (scons u s) (ren_etm rshift t) = subst_etm s t.
Proof. unfold subst_etm, ren_etm; rasimpl; reflexivity. Qed.

Lemma subst_up_cons_shift2_etm u s t :
  subst_etm (up_etm (scons u s)) (ren_etm rshift (ren_etm rshift t))
  = ren_etm rshift (subst_etm s t).
Proof. unfold subst_etm, ren_etm, up_etm; rasimpl; reflexivity. Qed.

(* the same as subst_up_shift_etm, three binders down: this is the shift that
   wrec's step carries in the induction hypothesis its computation rule
   supplies (Typing.Rules.wih_val). *)
Lemma subst_up3_shift_etm (g : nat -> etm) t :
  subst_etm (up_etm (up_etm (up_etm (up_etm g))))
            (ren_etm (up_ren (up_ren (up_ren rshift))) t)
  = ren_etm (up_ren (up_ren (up_ren rshift)))
            (subst_etm (up_etm (up_etm (up_etm g))) t).
Proof. unfold subst_etm, ren_etm, up_etm; rasimpl; reflexivity. Qed.
